#!/bin/bash

kargo_version()
{ 
  echo kargo - `jq -r ".version" package.json`
}

kargo_usage()
{
  kargo_version
  printf "usage: kargo [options] <command>\n\n"
  printf "options:\n"
  printf " -v, --version\t print the version and quit\n"
  printf " -h, --help\t print this help and quit\n\n"
  printf "commands:\n"
  printf " %-10s %-30s %s\n" "build" "<service>" "build the given service"  
  printf " %-10s %-30s %s\n" "configure" "" "generate the current configuration"
  printf " %-10s %-30s %s\n" "deploy" "<stack|all> [delay]" "deploy the given stack"
  printf " %-10s %-30s %s\n" "execute" "<script>" "exec the given script"    
  printf " %-10s %-30s %s\n" "info" "" "generate the current configuration"
  printf " %-10s %-30s %s\n" "pull" "" "pull the current workspace"
  printf " %-10s %-30s %s\n" "redeploy" "<stack|all>" "re deploy the given stack"  
  printf " %-10s %-30s %s\n" "remove" "<stack|all>" "remove the given stack"
  printf " %-10s %-30s %s\n" "use" "<workspace>" "select the given workspace"  
  printf "\n"
}

kargo_use()
{
  if [ -z "$1" ]; then 
    echo error: the command \"kargo use\" requires one argument.
    kargo_usage
    exit 1 
  fi
  # check whether the workspace exist
  if [ ! -d "$1" ]; then
    echo error: the specified workspace \"$1\" does not exist.
    exit 1
  fi
  # check whether a configuration has been created already. If yes clean it !
  if [ -d .kargo ]; then
    rm -fr .kargo
  fi
  echo WORKSPACE=$1 > .workspace
  echo switched to workspace \"$1\"
}

kargo_read_workspace()
{
  # check whether a workspace has been defined
  if [ ! -f ".workspace" ]; then
    echo error: no workspace defined
    echo tip: use the command \"kargo use \<workspace\>\" to define the workspace
    exit 1
  fi
  # read the workspace
  set -a
  . ./.workspace
  set +a
}

kargo_read_configuration()
{
  kargo_read_workspace
  # check whether the merged configuration has been made
  if [ ! -d ".kargo" ]; then
    echo error: no merged configuration
    echo tip: use the command \"kargo configure\" to generate the configuration
    exit 1
  fi
  # add kargo specific configuration
  KARGO_USER_ID=`id -u $USER`
  KARGO_GROUP_ID=`id -g $USER`
  KARGO_BUILD_PATH=$(dirname `realpath $0`)/.kargo
  KARGO_SCRIPTS_PATH="$KARGO_BUILD_PATH"/scripts
  # read the configuration
  set -a
  . .kargo/.env.default
  . .kargo/.env
  set +a
}

kargo_check_stack()
{
  if [ -z "$2" ]; then
    echo error: the command \"kargo $1\" requires one argument.
    kargo_usage
    exit 1
  fi
  kargo_read_configuration
  # Retrieve the list of stacks
  if [[ ! $STACKS =~ (^| )$2($| ) ]]; then
    if [ $2 != 'all' ]; then 
      echo error: the specified stack \"$2\" does not exist
      echo tip: use the command \"kargo info\" to list the available stacks
      exit 1
    fi
  fi
}

kargo_check_network()
{
  local EXISTING_NETWORK=`docker network ls | grep $1`
  if [ -z "$EXISTING_NETWORK" ]; then
    echo creating $1 network
    docker network create -d overlay --attachable $1
  fi
}

kargo_update_labels()
{
  local NODES=`docker node ls --format "{{.Hostname}}"`
  for NODE in $NODES; do
    local NODE_NAME=${NODE//-/_}
    local NODE_LABELS_VAR=${NODE_NAME^^}_LABELS
    local NODE_NEW_LABELS=${!NODE_LABELS_VAR}
    local NODE_EXISTING_LABELS=`docker node inspect -f '{{ range $k, $v := .Spec.Labels }}{{ $k }}={{ $v }} {{end}}' $NODE`
    # Keep the existing labels if needed
    for NODE_EXISTING_LABEL in $NODE_EXISTING_LABELS; do
      if [[ ! $NODE_NEW_LABELS =~ $NODE_EXISTING_LABEL ]]; then
        echo Removing $NODE_EXISTING_LABEL from $NODE_NAME
        local NODE_EXISTING_LABEL_KEY=${NODE_EXISTING_LABEL%=*}
        docker node update --label-rm $NODE_EXISTING_LABEL_KEY $NODE > /dev/null
      fi
    done
    # Add the label of needed
    for NODE_NEW_LABEL in $NODE_NEW_LABELS; do
      if [[ ! $NODE_EXISTING_LABELS =~ $NODE_NEW_LABEL ]]; then
        echo Adding $NODE_NEW_LABEL to $NODE_NAME
        docker node update --label-add $NODE_NEW_LABEL $NODE > /dev/null
      fi
    done
  done
}

kargo_configure()
{
  kargo_read_workspace
  # ensure the logs directory exists
  mkdir -p .kargo/logs
  # ensure the acme directory exists
  mkdir -p .kargo/acme
  # copy acme.json if required
  if [ ! -f .kargo/acme/acme.json ]; then
    if [ -f "$WORKSPACE"/acme.json ]; then
      cp "$WORKSPACE"/acme.json .kargo/acme/.
      chmod 600 .kargo/acme/acme.json
    fi
  fi
  # copy environment files
  cp .env.default .kargo/.env.default
  cp "$WORKSPACE"/.env .kargo/.
  kargo_read_configuration
  # build folder
  rm -fr .kargo/build
  cp -R ./build .kargo/build
  if [ -d "$WORKSPACE"/build ]; then
    cp -R "$WORKSPACE"/build .kargo/.
  fi
  # scripts folder
  rm -fr .kargo/scripts
  cp -R ./scripts .kargo/scripts
  if [ -d "$WORKSPACE"/scripts ]; then
    cp -R "$WORKSPACE"/scripts .kargo/.
  fi
  # deploy folder
  rm -fr .kargo/deploy
  cp -R ./deploy .kargo/deploy
  if [ -d "$WORKSPACE"/deploy ]; then
    cp -R "$WORKSPACE"/deploy .kargo/.
  fi
  # configs folder
  mkdir  /tmp/kargo
  cp -R ./configs /tmp/kargo
  if [ -d "$WORKSPACE"/configs ]; then
    cp -R "$WORKSPACE"/configs /tmp/kargo/.
  fi
  # template the require configuration files
  local TEMPLATES=`find /tmp/kargo/configs -name "*.tpl"`
  for TEMPLATE in $TEMPLATES; do
    envsubst < $TEMPLATE > ${TEMPLATE%.*}
  done
  # synchronize the configuration
  rsync -au --delete /tmp/kargo/configs .kargo/
  rm -fr /tmp/kargo
  kargo_update_labels
  echo workspace \"$WORKSPACE\" ready.
}

kargo_pull()
{
  kargo_read_workspace
  pushd $WORKSPACE > /dev/null
  git pull
  popd > /dev/null
}

kargo_info()
{
  kargo_read_configuration
  echo current user id/group id: $KARGO_USER_ID/$KARGO_GROUP_ID
  echo current workspace is: \"$WORKSPACE\"
  echo available stacks are:
  for STACK in $STACKS; do
    local STACK_NAME=${STACK^^}_STACK
    local STACK_CONTENT=${!STACK_NAME}
    printf " %-15s %s\n" $STACK "$STACK_CONTENT"
  done
}

kargo_build()
{
  kargo_read_configuration
  # check whether an agument is provided
  if [ -z "$1" ]; then
    echo error: the command \"kargo build\" requires one argument.
    kargo_usage
    exit 1
  fi
  # check whethet the argument is valid
  local SERVICE=$1.sh
  if [ ! -f ".kargo/build/$SERVICE" ]; then
    echo error: the specified service \"$1\" does not exist
    echo tip: use the commande \"kargo info\" to list the services to build
    exit 1
  fi
  pushd .kargo/build > /dev/null
  source ./$SERVICE
  popd > /dev/null
}

kargo_exec()
{
  kargo_read_configuration
  # check whether an agument is provided
  if [ -z "$1" ]; then
    echo error: the command \"kargo exec\" requires one argument.
    kargo_usage
    exit 1
  fi
  # check whethet the argument is valid
  local SCRIPT=$1.sh
  if [ ! -f ".kargo/scripts/$SCRIPT" ]; then
    echo error: the specified script \"$1\" does not exist
    echo tip: use the commande \"kargo info\" to list the available scripts
    exit 1
  fi
  pushd .kargo/scripts > /dev/null
  source ./$SCRIPT $2
  popd > /dev/null
}

kargo_deploy()
{
  kargo_check_stack deploy $1
  kargo_check_network $DOCKER_FRONT_NETWORK
  kargo_check_network $DOCKER_BACK_NETWORK
  if [ $1 == 'all' ]; then
    # deploy all stack
    local DELAY=${2:-5}
    for STACK in $STACKS; do
      echo deploying $STACK stack
      kargo_deploy $STACK
      echo waiting for $DELAY seconds
      sleep $DELAY
    done
  else
    # deploy the stack
    local STACK_NAME=${1^^}_STACK
    local STACK=${!STACK_NAME}
    local SERVICES_TO_DEPLOY=
    local AFTER_HOOKS_TO_RUN=
    pushd .kargo > /dev/null
    for SERVICE in $STACK; do
      echo initializing service $SERVICE
      SERVICES_TO_DEPLOY="$SERVICES_TO_DEPLOY -c deploy/$SERVICE.yml"
      local SERVICE_NAME=${SERVICE//-/_} # replace '-' by '_'
      SERVICE_NAME=${SERVICE_NAME^^} # change to uppercase
      local SERVICE_EXTENSION_NAME=${SERVICE_NAME}_EXTENSION
      local SERVICE_EXTENSION=${!SERVICE_EXTENSION_NAME}
      if [ "$SERVICE_EXTENSION" != "" ]; then
        SERVICES_TO_DEPLOY="$SERVICES_TO_DEPLOY -c deploy/$SERVICE_EXTENSION.yml"
      fi

      local SERVICE_BEFORE_HOOK=deploy/${SERVICE}_before.sh
      if [ -f "$SERVICE_BEFORE_HOOK" ]; then
        source $SERVICE_BEFORE_HOOK
      fi
      local SERVICE_AFTER_HOOK=deploy/${SERVICE}_after.sh
      if [ -f "$SERVICE_AFTER_HOOK" ]; then
        AFTER_HOOKS_TO_RUN="$AFTER_HOOKS_TO_RUN $SERVICE_AFTER_HOOK"
      fi

      # list services in the deploy file
      local DEPLOY_SERVICES=$(yq r --printMode p -P deploy/$SERVICE.yml 'services.*' | awk -F '.' '{ print $2 }')
      local YAML_CONSTRAINTS=""
      # foreach service, check if deploy constraints were specified in the .env
      for DEPLOY_SERVICE in $DEPLOY_SERVICES; do
        # normalize constraint env var (ie. arpege-loader => ARPEGE_LOADER_CONSTRAINTS)
        local UPPER_SERVICE=${DEPLOY_SERVICE^^}
        local CONSTRAINTS_NAME=${UPPER_SERVICE//-/_}_CONSTRAINTS
        local CONSTRAINTS=${!CONSTRAINTS_NAME}
        if [ "$CONSTRAINTS" != "" ]; then
          # generate yaml to declare deploy constraints
          YAML_CONSTRAINTS=$(printf "%s\n  %s:\n    deploy:\n      placement:\n        constraints:" "$YAML_CONSTRAINTS" "$DEPLOY_SERVICE")
          for CONSTRAINT in $CONSTRAINTS; do
            YAML_CONSTRAINTS=$(printf "%s\n          - %s" "$YAML_CONSTRAINTS" "$CONSTRAINT")
          done
        fi
      done
      # write constraints yaml file and add it to yaml files to load
      if [ "$YAML_CONSTRAINTS" != "" ]; then
        local YAML_FILE=deploy/$SERVICE-deploy-constraints.yml
        printf "version: '3.8'\n\nservices:%s\n" "$YAML_CONSTRAINTS" > $YAML_FILE
        SERVICES_TO_DEPLOY="$SERVICES_TO_DEPLOY -c $YAML_FILE"
      fi
    done
    docker stack deploy  --with-registry-auth $SERVICES_TO_DEPLOY kargo-$1
    for AFTER_HOOK in $AFTER_HOOKS_TO_RUN; do
      source $AFTER_HOOK
    done
    popd > /dev/null
  fi
  
}

kargo_redeploy()
{
  kargo_check_stack redeploy $1
  kargo_remove $1
  kargo_configure
  kargo_deploy $1
}

kargo_remove()
{
  kargo_check_stack remove $1
  if [ $1 == 'all' ]; then 
    local INVERSED_STACKS=
    for STACK in $STACKS; do
      INVERSED_STACKS="$STACK $INVERSED_STACKS"
    done
    for STACK in $INVERSED_STACKS; do
      echo removing $STACK stack
      kargo_remove $STACK
    done
  else
    docker stack rm kargo-$1
  fi
}


case $1 in
  -v|--version) kargo_version;;
  -h|--help) kargo_usage;;
  build) kargo_build "$2";;
  configure) kargo_configure;;
  deploy) kargo_deploy "$2" "$3";;
  exec) kargo_exec "$2" "$3";;
  info) kargo_info;;
  pull) kargo_pull;;
  redeploy) kargo_redeploy "$2";;  
  remove) kargo_remove "$2";;
  use) kargo_use "$2";;
  *) kargo_usage
esac


