apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.nameOverride | default (printf "%s-mongodb-operated" .Release.Name) }}
spec:
  members: {{ .Values.replicaCount }}
  type: ReplicaSet
  
  {{- if .Values.replicaSetHorizons }}
  replicaSetHorizons:
    {{- toYaml .Values.replicaSetHorizons | nindent 4 }}
  {{- end }}
  # important: control the version of the mongodb
  version: {{ .Values.version | default .Chart.AppVersion }}
  security:
    authentication:
      modes: ["SCRAM"]
    {{- if .Values.security.tls.enabled }}
    tls:
      caCertificateSecretRef:
        name: {{ .Values.security.tls.secretName }}
      certificateKeySecretRef:
        name: {{ .Values.security.tls.secretName }}
      enabled: true
    {{- end }}
  users:
    {{- with .Values.users  -}}
    {{ . | toYaml | nindent 4 }}
    {{- end}}
  statefulSet:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: mongod
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.extraVolumeMounts  }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.mongodbEnv  }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            - name: mongodb-agent
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.agent.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: {{ .Values.pvc.data.storageClass }}
            resources:
              requests:
                storage: {{ .Values.pvc.data.size }}
        {{- with .Values.extraVolumeClaimTemplates }}
          {{- toYaml . | nindent 8 }}
        {{ end -}}