{
 "title": "Swarm dashboard",
 "tags": [ "cAdvisor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, container_label_com_docker_stack_namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$stack\"}, container_label_com_docker_swarm_service_name)"
    }
   },
   {
    "name": "node",
    "label": "Hostname",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Displays CPU usage per service per node. If a service is replicated on a node with X tasks they'll be aggregated as one graph on the node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum without (cpu, container_label_com_docker_swarm_task_id) (irate(container_cpu_usage_seconds_total{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Displays memory usage per service per node. If a service is replicated on a node with X tasks they'll be aggregated as one graph on the node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(container_label_com_docker_swarm_task_id) (container_memory_working_set_bytes{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"})",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "description": "Displays network usage per service per node. If a service is replicated on a node with X tasks they'll be aggregated as one graph on the node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(interface, container_label_com_docker_swarm_task_id) (irate(container_network_receive_bytes_total{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} rx on {{instance}}"
    },
    {
     "expr": "sum without(interface, container_label_com_docker_swarm_task_id) (irate(container_network_transmit_bytes_total{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}[1m])) * -1",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} tx on {{instance}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Displays disk usage per service per node. If a service is replicated on a node with X tasks they'll be aggregated as one graph on the node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum without(container_label_com_docker_swarm_task_id) (irate(container_fs_reads_bytes_total{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}[1m]))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} read on {{instance}}"
    },
    {
     "expr": "sum without(container_label_com_docker_swarm_task_id) (irate(container_fs_writes_bytes_total{instance=~\"$node\", container_label_com_docker_stack_namespace=~\"$stack\",container_label_com_docker_swarm_service_name=~\"$service\"}[1m])) * -1",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}} write on {{instance}}"
    }
   ]
  }
 ]
}